apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-bytewax
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-bytewax
  template:
    metadata:
      labels:
        app: fastapi-bytewax
    spec:
      containers:
      - name: fastapi-bytewax
        image: fastapi-bytewax-app:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-bytewax
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: fastapi-bytewax
