components:
  bm25_retriever:
    init_parameters:
      document_store:
        init_parameters:
          api_key:
            env_vars:
            - ELASTIC_API_KEY
            strict: false
            type: env_var
          api_key_id:
            env_vars:
            - ELASTIC_API_KEY_ID
            strict: false
            type: env_var
          custom_mapping: null
          embedding_similarity_function: cosine
          hosts: http://localhost:9200
          index: small_embeddings
        type: haystack_integrations.document_stores.elasticsearch.document_store.ElasticsearchDocumentStore
      filter_policy: replace
      filters: {}
      fuzziness: AUTO
      scale_score: false
      top_k: 3
    type: haystack_integrations.components.retrievers.elasticsearch.bm25_retriever.ElasticsearchBM25Retriever
  document_joiner:
    init_parameters:
      join_mode: concatenate
      sort_by_score: true
      top_k: null
      weights: null
    type: haystack.components.joiners.document_joiner.DocumentJoiner
  embedding_retriever:
    init_parameters:
      document_store:
        init_parameters:
          api_key:
            env_vars:
            - ELASTIC_API_KEY
            strict: false
            type: env_var
          api_key_id:
            env_vars:
            - ELASTIC_API_KEY_ID
            strict: false
            type: env_var
          custom_mapping: null
          embedding_similarity_function: cosine
          hosts: http://localhost:9200
          index: small_embeddings
        type: haystack_integrations.document_stores.elasticsearch.document_store.ElasticsearchDocumentStore
      filter_policy: replace
      filters: {}
      num_candidates: null
      top_k: 3
    type: haystack_integrations.components.retrievers.elasticsearch.embedding_retriever.ElasticsearchEmbeddingRetriever
  llm:
    init_parameters:
      api_base_url: null
      api_key:
        env_vars:
        - OPENAI_API_KEY
        strict: true
        type: env_var
      generation_kwargs: {}
      http_client_kwargs: null
      model: gpt-4o-mini
      organization: null
      streaming_callback: null
      system_prompt: null
    type: haystack.components.generators.openai.OpenAIGenerator
  prompt_builder:
    init_parameters:
      required_variables:
      - documents
      - question
      template: "\nGiven the following information, answer the user's question.\n\
        If the information is not available in the provided documents, say that you\
        \ don't have enough information to answer.\n\nContext:\n{% for doc in documents\
        \ %}\n    {{ doc.content }}\n{% endfor %}\n\nQuestion: {{question}}\nAnswer:\n"
      variables: null
    type: haystack.components.builders.prompt_builder.PromptBuilder
  ranker:
    init_parameters:
      backend: torch
      batch_size: 16
      config_kwargs: null
      device:
        device: mps
        type: single
      document_prefix: ''
      embedding_separator: '

        '
      meta_fields_to_embed: []
      model: BAAI/bge-reranker-base
      model_kwargs: null
      query_prefix: ''
      scale_score: true
      score_threshold: null
      token:
        env_vars:
        - HF_API_TOKEN
        - HF_TOKEN
        strict: false
        type: env_var
      tokenizer_kwargs: null
      top_k: 3
      trust_remote_code: false
    type: haystack.components.rankers.sentence_transformers_similarity.SentenceTransformersSimilarityRanker
  text_embedder:
    init_parameters:
      api_base_url: null
      api_key:
        env_vars:
        - OPENAI_API_KEY
        strict: true
        type: env_var
      dimensions: null
      http_client_kwargs: null
      max_retries: null
      model: text-embedding-3-small
      organization: null
      prefix: ''
      suffix: ''
      timeout: null
    type: haystack.components.embedders.openai_text_embedder.OpenAITextEmbedder
connection_type_validation: true
connections:
- receiver: embedding_retriever.query_embedding
  sender: text_embedder.embedding
- receiver: document_joiner.documents
  sender: embedding_retriever.documents
- receiver: document_joiner.documents
  sender: bm25_retriever.documents
- receiver: ranker.documents
  sender: document_joiner.documents
- receiver: prompt_builder.documents
  sender: ranker.documents
- receiver: llm.prompt
  sender: prompt_builder.prompt
max_runs_per_component: 100
metadata: {}
